version: '3'

services:
  licenser:
    image: python:3.12-slim
    container_name: licenser
    restart: unless-stopped
    volumes:
      - ./:/app
      - pip_cache:/root/.cache/pip
    environment:
      - PYTHONPATH=/app:$PYTHONPATH
    working_dir: /app/src
    env_file:
      - ./src/.env
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "127.0.0.1:9000:8000"  # Bind to localhost for security, use reverse proxy for external access
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 256M

volumes:
    pip_cache:

